/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    Confetti: typeof import('./src/components/Confetti.vue')['default']
    Footer: typeof import('./src/components/Footer.vue')['default']
    MineBlock: typeof import('./src/components/MineBlock.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
